### ISSUE TITLE
Guidance for running application?

### ISSUE THREAD

**Issue by phuongvb** [wolf81/NoughtsAndCrosses#1]
Hello,

Can you please guide how to run this project?

After getting code, I jump into TicTacToeServer directory and run "swift build".  Error output:
"
../WebSocket_Mobile/NoughtsAndCrosses/TicTacToeServer/Sources/Game.swift:10:8: error: no such module 'TicTacToeShared'
import TicTacToeShared
"

If building TicTacToeServer success, then how can we run it on iOS?
If TicTacToeServer run success, it will open a socket when it launches, can we add a function on TicTacToe game, that allows a user to decide open or close socket?

**Comment by wolf81** [comment]
Hi, @phuongvb do you still need help with this?

**Comment by phuongvb** [comment]
Thank you for your response, I finished my task with WebSocket!
